export const POSTS = {
  SET_POSTS: 'SET_POSTS'
};

export const PAGES = {
  SET_PAGES: 'SET_PAGES'
};

export const INSTAGRAM = {
  SET_IMAGES: 'SET_IMAGES'
};

// searchText, categoryByLabel, mainPageByindex, archiveByMonthAndYear
export const FILTERS = {
  SET_MAIN_PAGE_INDEX: 'SET_MAIN_PAGE_INDEX',
  SET_POSTS_FILTER: 'SET_POSTS_FILTER',
  SET_SEARCH_TEXT: 'SET_SEARCH_TEXT',
  SET_CATEGORY_LABEL: 'SET_CATEGORY_LABEL',
  SET_ARCHIVE_MONTH: 'SET_ARCHIVE_MONTH',
  SET_ARCHIVE_YEAR: 'SET_ARCHIVE_YEAR'
};

export const FILTER_TYPE = {
  SEARCH: 'SEARCH',
  CATEGORY: 'CATEGORY',
  ARCHIVE: 'ARCHIVE'
};